// src/components/Nav.tsx
import React, { useState } from "react";
import { Link } from "@tanstack/react-router";
import { motion, Variants } from "framer-motion";

const itemVariants: Variants = {
  open: {
    opacity: 1,
    y: 0,
    transition: { type: "spring", stiffness: 300, damping: 24 },
  },
  closed: { opacity: 0, y: 20, transition: { duration: 0.2 } },
};

const Nav: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <nav className="sticky top-0 z-50 hidden p-6 text-lg font-bold xl:block dark:bg-dm-foreground/50">
      <ul className="flex items-center gap-6 dark:text-dm-primary-content">
        <li className="mr-auto text-2xl">
          <Link
            to="/"
            className="bg-gradient-to-r from-primary-dark from-25% via-red-500 via-60% to-yellow-300 to-90% bg-clip-text text-transparent"
          >
            BFTF Colorado
          </Link>
        </li>
        <li>
          <Link
            to="/"
            className="text-copy-lighter transition delay-100 duration-300 ease-in hover:text-primary-content"
          >
            Home
          </Link>
        </li>
        <li>
          <Link
            to="/supporters"
            className="text-copy-lighter transition delay-100 duration-300 ease-in hover:text-primary-content"
          >
            Supporters
          </Link>
        </li>
        {/*<li>*/}
        {/*  <Link*/}
        {/*    to="/services"*/}
        {/*    className="text-copy-lighter transition delay-100 duration-300 ease-in hover:text-primary-content"*/}
        {/*  >*/}
        {/*    Services*/}
        {/*  </Link>*/}
        {/*</li>*/}
        <li>
          <Link
            to="/bod"
            className="text-copy-lighter transition delay-100 duration-300 ease-in hover:text-primary-content"
          >
            Board of Directors
          </Link>
        </li>
        {/*<li>*/}
        {/*  <Link*/}
        {/*    to="/news"*/}
        {/*    className="text-copy-lighter transition delay-100 duration-300 ease-in hover:text-primary-content"*/}
        {/*  >*/}
        {/*    In the News*/}
        {/*  </Link>*/}
        {/*</li>*/}
        <motion.nav
          onHoverStart={() => setIsOpen(true)}
          initial={false}
          animate={isOpen ? "open" : "closed"}
          className="relative flex"
        >
          <motion.button
            whileTap={{ scale: 0.97 }}
            onClick={() => setIsOpen(!isOpen)}
            className="flex items-center gap-1.5 fill-copy-lighter text-copy-lighter"
          >
            Events & Partners
            <motion.div
              variants={{
                open: { rotate: 180 },
                closed: { rotate: 0 },
              }}
              transition={{ duration: 0.2 }}
              style={{ originY: 0.55 }}
            >
              <svg width="15" height="15" viewBox="0 0 20 20">
                <path d="M0 7 L 20 7 L 10 16" />
              </svg>
            </motion.div>
          </motion.button>
          <motion.ul
            onHoverEnd={() => setIsOpen(false)}
            className="absolute right-0 top-6 grid w-max gap-3 p-6 text-right text-sm dark:bg-dm-foreground/85"
            variants={{
              open: {
                clipPath: "inset(0% 0% 0% 0% round 10px)",
                transition: {
                  type: "spring",
                  bounce: 0,
                  duration: 0.7,
                  delayChildren: 0.3,
                  staggerChildren: 0.05,
                },
              },
              closed: {
                clipPath: "inset(10% 50% 90% 50% round 10px)",
                transition: {
                  type: "spring",
                  bounce: 0,
                  duration: 0.3,
                },
              },
            }}
            style={{ pointerEvents: isOpen ? "auto" : "none" }}
          >
            <motion.li className="ml-auto flex items-end" variants={itemVariants}>
              <a
                href="http://www.bitnermemorialfund.org/"
                target="_blank"
                className="text-copy-lighter transition delay-100 duration-300 ease-in hover:text-primary-content"
              >
                Bitner Memorial 5K/10K
              </a>
              <svg width="21" height="21" viewBox="0 0 21 21">
                <motion.path
                  d="M10.0002 5H8.2002C7.08009 5 6.51962 5 6.0918 5.21799C5.71547 5.40973 5.40973 5.71547 5.21799 6.0918C5 6.51962 5 7.08009 5 8.2002V15.8002C5 16.9203 5 17.4801 5.21799 17.9079C5.40973 18.2842 5.71547 18.5905 6.0918 18.7822C6.5192 19 7.07899 19 8.19691 19H15.8031C16.921 19 17.48 19 17.9074 18.7822C18.2837 18.5905 18.5905 18.2839 18.7822 17.9076C19 17.4802 19 16.921 19 15.8031V14M20 9V4M20 4H15M20 4L13 11"
                  fill="transparent"
                  strokeWidth="2"
                  stroke="#5e616e"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </motion.li>
            <motion.li className="ml-auto flex items-end" variants={itemVariants}>
              <a
                href="http://www.odmp.org/"
                target="_blank"
                className="text-copy-lighter transition delay-100 duration-300 ease-in hover:text-primary-content"
              >
                ODMP
              </a>
              <svg width="21" height="21" viewBox="0 0 21 21">
                <motion.path
                  d="M10.0002 5H8.2002C7.08009 5 6.51962 5 6.0918 5.21799C5.71547 5.40973 5.40973 5.71547 5.21799 6.0918C5 6.51962 5 7.08009 5 8.2002V15.8002C5 16.9203 5 17.4801 5.21799 17.9079C5.40973 18.2842 5.71547 18.5905 6.0918 18.7822C6.5192 19 7.07899 19 8.19691 19H15.8031C16.921 19 17.48 19 17.9074 18.7822C18.2837 18.5905 18.5905 18.2839 18.7822 17.9076C19 17.4802 19 16.921 19 15.8031V14M20 9V4M20 4H15M20 4L13 11"
                  fill="transparent"
                  strokeWidth="2"
                  stroke="#5e616e"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </motion.li>
          </motion.ul>
        </motion.nav>
        <li>
          <a
            target="_blank"
            href="https://www.paypal.com/paypalme/brotherhoodaurora"
            className="rounded-md bg-primary px-4 py-3 dark:bg-dm-primary"
          >
            SUPPORT US
          </a>
        </li>
      </ul>
    </nav>
  );
};

export default Nav;

// src/lib/components/Nav.svelte
<script lang="ts">
  import { page } from "$app/state";

  type Theme = "light" | "dark";

  const links = [
    { href: "/", label: "Home" },
    { href: "/supporters", label: "Supporters" },
    { href: "/bod", label: "Board of Directors" }
  ];

  const partnerLinks = [
    { href: "http://www.bitnermemorialfund.org/", label: "Bitner Memorial 5K/10K" },
    { href: "http://www.odmp.org/", label: "ODMP" }
  ];

  let mobileOpen = $state(false);
  let partnerOpen = $state(false);
  let { theme = "light", onThemeToggle } = $props<{ theme?: Theme; onThemeToggle: () => void }>();

  const isActive = (href: string) => (href === "/" ? page.url.pathname === "/" : page.url.pathname.startsWith(href));

  const closeMenus = () => {
    mobileOpen = false;
    partnerOpen = false;
  };
</script>

<header class="site-header">
  <div class="header-inner">
    <button
      class="theme-toggle"
      class:is-dark={theme === "dark"}
      type="button"
      onclick={onThemeToggle}
      aria-label={theme === "dark" ? "Switch to light mode" : "Switch to dark mode"}
    >
      <span class="icon sun" aria-hidden="true">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round">
          <circle cx="12" cy="12" r="4.2" />
          <path d="M12 2.5v2.2M12 19.3v2.2M4.9 4.9l1.6 1.6M17.5 17.5l1.6 1.6M2.5 12h2.2M19.3 12h2.2M4.9 19.1l1.6-1.6M17.5 6.5l1.6-1.6" />
        </svg>
      </span>
      <span class="icon moon" aria-hidden="true">
        <svg viewBox="0 0 24 24" fill="currentColor">
          <path d="M19.2 14.8a8.4 8.4 0 0 1-10-10A9.2 9.2 0 1 0 21 16.6a7.6 7.6 0 0 1-1.8-1.8z" />
        </svg>
      </span>
    </button>

    <nav class="desktop-nav" aria-label="Primary navigation">
      <a class="brand" href="/">BFTF Colorado</a>

      {#each links as link}
        <a class:active={isActive(link.href)} href={link.href}>{link.label}</a>
      {/each}

      <div class="dropdown" role="presentation" onmouseenter={() => (partnerOpen = true)} onmouseleave={() => (partnerOpen = false)}>
        <button aria-expanded={partnerOpen} type="button" onclick={() => (partnerOpen = !partnerOpen)}>
          Events &amp; Partners
          <span class:chevOpen={partnerOpen}>⌄</span>
        </button>
        {#if partnerOpen}
          <div class="dropdown-menu">
            {#each partnerLinks as partner}
              <a href={partner.href} target="_blank" rel="noreferrer">{partner.label}</a>
            {/each}
          </div>
        {/if}
      </div>

      <a class="donate" href="https://www.paypal.com/paypalme/brotherhoodaurora" target="_blank" rel="noreferrer"> Support Us </a>
    </nav>

    <nav class="mobile-nav" aria-label="Mobile navigation">
      <a class="brand" href="/" onclick={closeMenus}>BFTF Colorado</a>
      <button class="hamburger" aria-expanded={mobileOpen} type="button" onclick={() => (mobileOpen = !mobileOpen)}> ☰ </button>

      {#if mobileOpen}
        <div class="mobile-panel">
          {#each links as link}
            <a class:active={isActive(link.href)} href={link.href} onclick={closeMenus}>{link.label}</a>
          {/each}

          <div class="mobile-group">Events &amp; Partners</div>
          {#each partnerLinks as partner}
            <a class="partner-link" href={partner.href} target="_blank" rel="noreferrer">{partner.label}</a>
          {/each}

          <a class="donate" href="https://www.paypal.com/paypalme/brotherhoodaurora" target="_blank" rel="noreferrer"> Support Us </a>
        </div>
      {/if}
    </nav>
  </div>
</header>

<style lang="scss">
  .site-header {
    position: sticky;
    top: 0;
    z-index: 40;
    backdrop-filter: blur(10px);
    background: var(--header-bg);
    border-bottom: 1px solid rgba(16, 35, 73, 0.08);
  }

  .header-inner {
    width: 100%;
    position: relative;
  }

  .desktop-nav,
  .mobile-nav {
    margin: 0 auto;
    width: min(1100px, 94vw);
    display: flex;
    align-items: center;
    gap: 1rem;
    padding: 0.85rem 3.5rem 0.85rem 0;
  }

  .brand {
    margin-right: auto;
    font-size: 1.35rem;
    font-weight: 800;
    text-decoration: none;
    letter-spacing: 0.02em;
    background: linear-gradient(112deg, #5f98ff, #f2828a 56%, #f4cd72);
    -webkit-background-clip: text;
    background-clip: text;
    color: transparent;
    -webkit-text-stroke: 0.45px rgba(0, 0, 0, 0.45);
  }

  :global(html[data-theme="dark"]) .brand {
    background: linear-gradient(112deg, var(--brand), var(--danger) 56%, var(--accent));
    -webkit-background-clip: text;
    background-clip: text;
    color: transparent;
    -webkit-text-stroke: 0 transparent;
  }

  a {
    text-decoration: none;
    font-weight: 600;
    color: var(--muted);
    transition: color 160ms ease;

    &:hover,
    &.active {
      color: var(--brand);
    }
  }

  .dropdown {
    position: relative;

    button {
      border: 0;
      background: transparent;
      font: inherit;
      color: var(--muted);
      cursor: pointer;
      display: inline-flex;
      align-items: center;
      gap: 0.3rem;
      font-weight: 600;
    }
  }

  .dropdown-menu {
    position: absolute;
    right: 0;
    top: calc(100% + 0.6rem);
    width: max-content;
    display: grid;
    gap: 0.5rem;
    padding: 0.8rem;
    border: 1px solid var(--border);
    border-radius: 0.8rem;
    background: var(--surface);
    box-shadow: var(--shadow);

    a {
      padding: 0.2rem 0.4rem;
    }
  }

  .donate {
    background: linear-gradient(120deg, var(--brand), var(--brand-strong));
    color: #fff;
    border-radius: 0.65rem;
    padding: 0.65rem 0.95rem;

    &:hover {
      color: #fff;
      filter: brightness(1.08);
    }
  }

  .theme-toggle {
    position: absolute;
    top: 50%;
    right: max(0.65rem, env(safe-area-inset-right));
    transform: translateY(-50%);
    z-index: 30;
    width: 2.5rem;
    height: 2.5rem;
    border-radius: 999px;
    border: 1px solid var(--border);
    background: var(--surface);
    color: var(--brand);
    box-shadow: var(--shadow-soft);
    cursor: pointer;
    display: grid;
    place-items: center;
    overflow: hidden;
    isolation: isolate;
    transition:
      border-color 180ms ease,
      transform 180ms ease,
      color 180ms ease;

    &::before {
      content: "";
      position: absolute;
      inset: -55%;
      background: conic-gradient(from 0deg, transparent, rgba(95, 152, 255, 0.35), transparent 42%);
      opacity: 0;
      transform: rotate(0deg);
      transition: opacity 200ms ease;
      animation: spin 1.8s linear infinite;
      z-index: -1;
    }

    &:hover {
      transform: translateY(calc(-50% - 1px));
      border-color: var(--brand);
      color: var(--brand-strong);

      &::before {
        opacity: 1;
      }
    }

    .icon {
      position: absolute;
      width: 1.25rem;
      height: 1.25rem;
      display: grid;
      place-items: center;
      transition:
        opacity 260ms ease,
        transform 360ms cubic-bezier(0.22, 1, 0.36, 1);

      svg {
        width: 100%;
        height: 100%;
      }
    }

    .sun {
      opacity: 1;
      transform: rotate(0deg) scale(1);
    }

    .moon {
      opacity: 0;
      transform: rotate(-80deg) scale(0.35);
    }

    &.is-dark {
      .sun {
        opacity: 0;
        transform: rotate(90deg) scale(0.32);
      }

      .moon {
        opacity: 1;
        transform: rotate(0deg) scale(1);
      }
    }
  }

  .chevOpen {
    transform: rotate(180deg);
  }

  .mobile-nav {
    display: none;
  }

  .hamburger {
    border: 1px solid var(--border);
    border-radius: 0.65rem;
    background: var(--surface);
    width: 2.35rem;
    height: 2.35rem;
    font-size: 1.2rem;
  }

  .mobile-panel {
    position: absolute;
    left: 3vw;
    right: 3vw;
    top: calc(100% + 0.5rem);
    z-index: 20;
    display: grid;
    gap: 0.8rem;
    padding: 1rem;
    border: 1px solid var(--border);
    border-radius: 1rem;
    background: var(--surface);
    box-shadow: var(--shadow);

    .mobile-group {
      margin-top: 0.2rem;
      color: var(--text);
      font-weight: 700;
      font-size: 0.92rem;
    }

    .partner-link {
      font-size: 0.94rem;
    }

    .donate {
      text-align: center;
    }
  }

  @keyframes spin {
    to {
      transform: rotate(1turn);
    }
  }

  @media (max-width: 920px) {
    .desktop-nav {
      display: none;
    }

    .mobile-nav {
      display: flex;
      position: relative;
      padding-right: 3.2rem;
    }

    .theme-toggle {
      top: 50%;
      width: 2.3rem;
      height: 2.3rem;
    }
  }
</style>
